---
title: "Modeling Assignment 2"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(pROC)
library(MLmetrics)
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}
bank = read_rds("../../BankChurners.rds") 
```


## Feature Engineering

```{r}
# create some cool features. Make sure you add comments so I know what you are trying to accomplish!

#first try
library(forcats)
library(dplyr)

#EDA
glimpse(bank)
sum(is.na(bank))
dim(bank)
unique(bank$Education_Level)
unique(bank$Marital_Status)
unique(bank$Card_Category)
unique(bank$Income_Category)

bank %>%
    group_by(Churn) %>%
    count()

#engineering some features
#encoding categorical data
bank1 <- bank %>%
    mutate(gender = if_else(Gender=="M",1,0)) %>%
    select(-Gender) %>%
    mutate(married = if_else(Marital_Status=="Married",1,0)) %>%
    mutate(single = if_else(Marital_Status=="Single",1,0)) %>%
    mutate(divorced = if_else(Marital_Status=="Divorced",1,0)) %>%
    mutate(ms_unknown = if_else(Marital_Status=="Unknown",1,0)) %>%
    select(-Marital_Status) %>%
    mutate(blue = if_else(Card_Category=="Blue",1,0)) %>%
    mutate(gold = if_else(Card_Category=="Gold",1,0)) %>%
    mutate(silver = if_else(Card_Category=="Silver",1,0)) %>%
    mutate(platinum = if_else(Card_Category=="Platinum",1,0)) %>%
    select(-Card_Category) %>%
    mutate(ed_level = Education_Level %>% 
           fct_recode("Unknown" = "Unknown",
                      "Uneducated" = "Uneducated",
                      "High School" = "High School",
                      "College" = "College",
                      "Graduate" = "Graduate",
                      "Post-Graduate" = "Post-Graduate",
                      "Doctorate" = "Doctorate") %>%
           as.integer()) %>%
    select(-Education_Level) %>%
    mutate(income = Income_Category %>% 
           fct_recode("Unknown" = "Unknown",
                      "low" = "Less than $40K",
                      "lowmed" = "40K - $60K",
                      "med" = "$60K - $80K",
                      "medhigh" = "$80K - $120K",
                      "high" = "$120K +") %>%
           as.integer()) %>%
    select(-Income_Category)

bank2 <- bank1 %>%
    mutate(churn = if_else(Churn=="yes",1,0)) %>%
    select(-Churn)

round(cor(bank2), digits = 2)

cor(bank2$churn, bank2$Total_Trans_Ct)
cor(bank2$churn, bank2$Total_Ct_Chng_Q4_Q1)
cor(bank2$churn, bank2$Total_Revolving_Bal)
cor(bank2$churn, bank2$Total_Relationship_Count)
cor(bank2$churn, bank2$Contacts_Count_12_mon)


# bank3 <- bank1 %>%
#     select(Churn, Total_Trans_Ct, Total_Ct_Chng_Q4_Q1, Total_Revolving_Bal, Total_Relationship_Count, Contacts_Count_12_mon)

bank3 <- bank1 %>% 
  select(Credit_Limit, Customer_Age, Total_Revolving_Bal, Total_Trans_Ct,
         Total_Trans_Amt, Churn)

print(ncol(bank3)) # Only 5 features allowed for project 2! Not counting the dependent variable.
```

#template from Hendrik
## Specification

```{r}
# specify the model to be used (i.e. KNN, Naive Bayes, decision tree, random forest, bagged trees) and the tuning parameters used

ctrl <- trainControl(method = "cv", number = 3, classProbs = TRUE, summaryFunction = twoClassSummary)
set.seed(504) 

bank_index <- createDataPartition(bank3$Churn, p = 0.80, list = FALSE)
train <- bank3[ bank_index, ]
test <- bank3[-bank_index, ]

# example spec for rf
fit <- train(Churn ~ .,
             data = train, 
             method = "rf",
             ntree = 20, 
             tuneLength = 3,
             metric = "ROC",
             trControl = ctrl)

fit

confusionMatrix(predict(fit, test),factor(test$Churn))
```


## Best model

```{r}
# Here are a few lines to inspect your best model. Add some comments about optimal hyperparameters.
print(fit)
print(fit$bestTune)
```


## Re-fit and evaluation

```{r}
# the "method" below should match the one you chose above. 

set.seed(1504) # I will choose a different seed for evaluation

bank_index <- createDataPartition(bank3$Churn, p = 0.80, list = FALSE)
train <- bank3[ bank_index, ]
test <- bank3[-bank_index, ]

# example spec for rf
fit_final <- train(Churn ~ .,
             data = train, 
             method = "rf",
             tuneGrid=fit$bestTune,
             metric = "ROC",
             trControl = ctrl) 
# The last line means we will fit a model using the best tune parameters your CV found above.

myRoc <- roc(test$Churn, predict(fit_final, test, type="prob")[,2])

plot(myRoc)
auc(myRoc)
```

