---
title: "Modeling Assignment 2"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(pROC)
library(MLmetrics)
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}
bank = read_rds("../../BankChurners.rds") 
```


## Feature Engineering

```{r}
library(forcats)
library(dplyr)

#engineering some features/encoding categorical data
bank1 <- bank %>%
    select(-c(2,4:7))


#to check if any columns have a standard deviation of zero
zero_sd_cols <- apply(bank, 2, sd) == 0

```

#PCA
```{r}

#Run the principle component analysis
pr_bank <- prcomp(x = select(bank1, -Churn), scale = T, center = T)
summary(pr_bank)

#Show variance plot
screeplot(pr_bank, type = "lines")

#Visualize biplots
biplot(pr_bank)
biplot(pr_bank, choices = c(3,4))

```


#Factor loadings
```{r}

#Factor loadings
pr_bank$rotation

#Loadings times values for all rows
head(pr_bank$x)

#
# Get factor loadings for first principal component
pc1_loadings <- pr_bank$rotation[, 1]

# Sort factor loadings in descending order
pc1_loadings_sorted <- sort(pc1_loadings, decreasing = TRUE)

# Print sorted factor loadings for PC1
pc1_loadings_sorted

```


## With engineered features base on higher PC catagories
```{r}
# Credit_Limit
# Total_Trans_Ct
# Customer_Age
# single (---lowers)
# Total_Revolving_Bal
# 
# Avg_Open_To_Buy
# Credit_Limit
# Avg_Utilization_Ratio
# Total_Trans_Ct
# Total_Trans_Amt
# Avg_Utilization_Ratio
# Customer_Age
# Dependent_count
# Months_on_book

#original from continuous plus categorical 
#select(Total_Trans_Amt, Total_Trans_Ct, Customer_Age, Total_Revolving_Bal, Churn)

bankoJD <- bank1 %>% 
  select(Credit_Limit, Customer_Age, Total_Revolving_Bal, Total_Trans_Ct,
         Total_Trans_Amt, Churn)

#removing Total_Trans_Amt dropped it from .7168 to .5ish
#removing Total_Trans_Ct dropped from .7168 to .62
#removing Avg_Utilization_Ratio dropped from .7168 to .69
#removing Credit_Limit dropped from .7168 to .69

#removing Avg_Open_To_Buy dropped from .7168 to .70
#removing Avg_Open_To_Buy and adding Avg_Utilization_Ratio .7114
#removing Avg_Open_To_Buy and adding Customer_Age .7328
#    (Credit_Limit, Customer_Age, Avg_Utilization_Ratio, Total_Trans_Ct,
#     Total_Trans_Amt, Churn)
#removing Credit_Limit and adding Avg_Utilization_Ratio .6984
#removing Credit_Limit and adding Months_on_book .7046

#continuous first 5:  select(Avg_Open_To_Buy, Credit_Limit, Avg_Utilization_Ratio, Total_Trans_Ct, Total_Trans_Amt, Churn)
  #with categorical: select(Credit_Limit, Total_Trans_Ct, Customer_Age, Total_Revolving_Bal, Churn)

print(ncol(bankoJD)) # Only 5 features allowed! Not counting the dependent variable.

```


## Loading for modified data frame
```{r}
#Run the principle component analysis
pr_bank <- prcomp(x = select(bankoJD, -Churn), scale = T, center = T)
summary(pr_bank)

head(pr_bank$x)

# Get factor loadings for first principal component
pc1_loadings <- pr_bank$rotation[, 1]

# Sort factor loadings in descending order
pc1_loadings_sorted <- sort(pc1_loadings, decreasing = TRUE)

# Print sorted factor loadings for PC1
pc1_loadings_sorted

```


## Model with engineered features base on higher PC catagories
```{r}
set.seed(504) 

ctrl <- trainControl(method = "cv", number = 5, classProbs=TRUE, summaryFunction = twoClassSummary)

bank_index <- createDataPartition(bankoJD$Churn, p = 0.80, list = FALSE)
train <- bankoJD[ bank_index, ]
test <- bankoJD[-bank_index, ]

fit <- train(Churn ~ .,
             data = train,
             method = "rf",
             metric = "ROC",
             #preProcess = c("center", "scale"),
             trControl = ctrl)

confusionMatrix(predict(fit, test),factor(test$Churn))

```






#template from Hendrik
## Specification

```{r}
# specify the model to be used (i.e. KNN, Naive Bayes, decision tree, random forest, bagged trees) and the tuning parameters used

ctrl <- trainControl(method = "cv", number = 5, classProbs=TRUE, summaryFunction = twoClassSummary)

bank_index <- createDataPartition(bankoJD$Churn, p = 0.80, list = FALSE)
train <- bankoJD[ bank_index, ]
test <- bankoJD[-bank_index, ]

# example spec for rf
fit <- train(Churn ~ .,
             data = train, 
             method = "rf",
             metric = "ROC",
             trControl = ctrl)

fit

confusionMatrix(predict(fit, test),factor(test$Churn))

```


## Best model

```{r}
# Here are a few lines to inspect your best model. Add some comments about optimal hyperparameters.
print(fit)
print(fit$bestTune)
```


## Re-fit and evaluation

```{r}
# the "method" below should match the one you chose above. 

set.seed(1504) # I will choose a different seed for evaluation

bank_index <- createDataPartition(bankoJD$Churn, p = 0.80, list = FALSE)
train <- bankoJD[ bank_index, ]
test <- bankoJD[-bank_index, ]

# example spec for rf
fit_final <- train(Churn ~ .,
             data = train, 
             method = "rf",
             tuneGrid=fit$bestTune,
             metric = "ROC",
             trControl = ctrl) 
# The last line means we will fit a model using the best tune parameters your CV found above.

myRoc <- roc(test$Churn, predict(fit_final, test, type="prob")[,2])

plot(myRoc)
auc(myRoc)
```

