---
title: "Modeling Assignment 2"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(pROC)
library(MLmetrics)
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}
bank = read_rds("../../BankChurners.rds") 
```


## Feature Engineering

```{r}
# create some cool features. Make sure you add comments so I know what you are trying to accomplish!
# banko <- bank %>% 
#   mutate(age2=Customer_Age^2) %>%
#   select(Customer_Age, age2, Card_Category, Education_Level, Dependent_count, Churn)
  # Please do use some PCA! Doesn't have to be all 5 features!

#removing categorical features
banko <- bank %>%
    select(-c(2,4:7,20))

```


# PCA
```{r}
mypr <- prcomp(banko, scale = TRUE)

summary(mypr)
plot(mypr, type ="l")
biplot(mypr, scale = 0)

```

# Extract PC scores
```{r}
str(mypr)

mypr$x

prc <- bind_cols(bank, mypr$x)

head(prc)

```


```{r}
bankoJD <- prc %>% 
  select(Credit_Limit, Customer_Age, Total_Revolving_Bal, Total_Trans_Ct,
         Total_Trans_Amt, Churn)
 #removing Total_Trans_Amt dropped it from .7168 to .5ish
#removing Total_Trans_Ct dropped from .7168 to .62
#removing Avg_Utilization_Ratio dropped from .7168 to .69
#removing Credit_Limit dropped from .7168 to .69

```


## Specification

```{r}
# specify the model to be used (i.e. KNN, Naive Bayes, decision tree, random forest, bagged trees) and the tuning parameters used

ctrl <- trainControl(method = "cv", number = 3, classProbs=TRUE, summaryFunction = twoClassSummary)
set.seed(504) 

bank_index <- createDataPartition(bankoJD$Churn, p = 0.80, list = FALSE)
train <- bankoJD[ bank_index, ]
test <- bankoJD[-bank_index, ]

# example spec for rf
fit <- train(Churn ~ .,
             data = train, 
             method = "rf",
#             ntree = 20,
#             tuneLength = 3,
             metric = "ROC",
             trControl = ctrl)

#fit

confusionMatrix(predict(fit, test),factor(test$Churn))
```


## Best model

```{r}
# Here are a few lines to inspect your best model. Add some comments about optimal hyperparameters.
print(fit)
print(fit$bestTune)
```


## Re-fit and evaluation

```{r}
# the "method" below should match the one you chose above. 

set.seed(1504) # I will choose a different seed for evaluation

bank_index <- createDataPartition(bankoJD$Churn, p = 0.80, list = FALSE)
train <- bankoJD[ bank_index, ]
test <- bankoJD[-bank_index, ]

# example spec for rf
fit_final <- train(Churn ~ .,
             data = train, 
             method = "rf",
             tuneGrid=fit$bestTune,
             metric = "ROC",
             trControl = ctrl) 
# The last line means we will fit a model using the best tune parameters your CV found above.

myRoc <- roc(test$Churn, predict(fit_final, test, type="prob")[,2])

plot(myRoc)
auc(myRoc)
```

