---
title: "Modeling Assignment 2"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(caret)
library(pROC)
library(MLmetrics)
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r}
bank = read_rds("../BankChurners.rds") 
```


## Feature Engineering

```{r}
# create some cool features. Make sure you add comments so I know what you are trying to accomplish!
#banko <- bank %>% 
#  mutate(age2=Customer_Age^2) %>%
#  select(Customer_Age, age2, Card_Category, Education_Level, Dependent_count, Churn)
  # Please do use some PCA! Doesn't have to be all 5 features!



#print(ncol(banko)) # Only 5 features allowed for project 2! Not counting the dependent variable.

#my try
library(forcats)
library(dplyr)

#EDA
glimpse(bank)
sum(is.na(bank))
dim(bank)
unique(bank$Education_Level)
unique(bank$Marital_Status)
unique(bank$Card_Category)
unique(bank$Income_Category)
 
#engineering some features/encoding categorical data
bank1 <- bank %>%
    mutate(gender = if_else(Gender=="M",1,0)) %>%
    select(-Gender) %>%
    mutate(married = if_else(Marital_Status=="Married",1,0)) %>%
    mutate(single = if_else(Marital_Status=="Single",1,0)) %>%
    mutate(divorced = if_else(Marital_Status=="Divorced",1,0)) %>%
    mutate(ms_unknown = if_else(Marital_Status=="Unknown",1,0)) %>%
    select(-Marital_Status) %>%
    mutate(blue = if_else(Card_Category=="Blue",1,0)) %>%
    mutate(gold = if_else(Card_Category=="Gold",1,0)) %>%
    mutate(silver = if_else(Card_Category=="Silver",1,0)) %>%
    mutate(platinum = if_else(Card_Category=="Platinum",1,0)) %>%
    select(-Card_Category) %>%
    mutate(ed_level = Education_Level %>% 
           fct_recode("Unknown" = "Unknown",
                      "Uneducated" = "Uneducated",
                      "High School" = "High School",
                      "College" = "College",
                      "Graduate" = "Graduate",
                      "Post-Graduate" = "Post-Graduate",
                      "Doctorate" = "Doctorate") %>%
           as.integer()) %>%
    select(-Education_Level) %>%
    mutate(income = Income_Category %>% 
           fct_recode("Unknown" = "Unknown",
                      "low" = "Less than $40K",
                      "lowmed" = "40K - $60K",
                      "med" = "$60K - $80K",
                      "medhigh" = "$80K - $120K",
                      "high" = "$120K +") %>%
           as.integer()) %>%
    select(-Income_Category)
    

#to check if any columns have a standard deviation of zero
zero_sd_cols <- apply(bank, 2, sd) == 0

```

#PCA
```{r}

#Run the principle component analysis
pr_bank <- prcomp(x = select(bank1, -Churn), scale = T, center = T)
summary(pr_bank)

#Show variance plot
screeplot(pr_bank, type = "lines")

#Visualize biplots
biplot(pr_bank)
biplot(pr_bank, choices = c(3,4))

```


#Factor loadings
```{r}

#Factor loadings
pr_bank$rotation

#Loadings times values for all rows
head(pr_bank$x)

#
# Get factor loadings for first principal component
pc1_loadings <- pr_bank$rotation[, 1]

# Sort factor loadings in descending order
pc1_loadings_sorted <- sort(pc1_loadings, decreasing = TRUE)

# Print sorted factor loadings for PC1
pc1_loadings_sorted

```
#PCA 2
```{r}
#PCA2
# Get factor loadings for first principal component
pc2_loadings <- pr_bank$rotation[, 2]

# Sort factor loadings in descending order
pc2_loadings_sorted <- sort(pc2_loadings, decreasing = TRUE)

# Print sorted factor loadings for PC2
pc2_loadings_sorted
```
#PCA 3
```{r}
#PCA2
# Get factor loadings for first principal component
pc3_loadings <- pr_bank$rotation[, 3]

# Sort factor loadings in descending order
pc3_loadings_sorted <- sort(pc3_loadings, decreasing = TRUE)

# Print sorted factor loadings for PC3
pc3_loadings_sorted
```

#PCA4
```{r}
#PCA2
# Get factor loadings for first principal component
pc4_loadings <- pr_bank$rotation[, 4]

# Sort factor loadings in descending order
pc4_loadings_sorted <- sort(pc4_loadings, decreasing = TRUE)

# Print sorted factor loadings for PC4
pc4_loadings_sorted
```
#PCA5
```{r}
#PCA2
# Get factor loadings for first principal component
pc5_loadings <- pr_bank$rotation[, 5]

# Sort factor loadings in descending order
pc5_loadings_sorted <- sort(pc5_loadings, decreasing = TRUE)

# Print sorted factor loadings for PC5
pc5_loadings_sorted
```



#naming components
```{r}

#Add Churn label to principle components and name them
prc <- bind_cols(select(bank1,Churn),as.data.frame(pr_bank$x)) %>%
  select(1:6) %>%
  rename("bluesilver_avgopen_credit" = PC1) %>%
  rename("high_user" = PC2) %>%
  rename("older_oldacct" = PC3) %>%
  rename("single_highbalance" = PC4) %>%
  rename("highbal_utilratio" = PC5)
head(prc)

#Density of different components by churn (Factors 1&2)
prc %>%
  select(Churn, bluesilver_avgopen_credit, high_user) %>%
  pivot_longer(cols = -Churn,names_to = "component",values_to = "loading") %>%
  ggplot(aes(loading, fill=Churn))+
  geom_density(alpha=0.5)+
  facet_grid(.~component)

#Density of different components by churn (Factors 3&4)
prc %>%
  select(Churn, older_oldacct, single_highbalance) %>%
  pivot_longer(cols = -Churn,names_to = "component",values_to = "loading") %>%
  ggplot(aes(loading, fill=Churn))+
  geom_density(alpha=0.5)+
  facet_grid(.~component)

#Density of different components by churn (Factors 4&5)
prc %>%
  select(Churn, single_highbalance, highbal_utilratio) %>%
  pivot_longer(cols = -Churn,names_to = "component",values_to = "loading") %>%
  ggplot(aes(loading, fill=Churn))+
  geom_density(alpha=0.5)+
  facet_grid(.~component)

#tried all components
prc %>%
  select(Churn, bluesilver_avgopen_credit, high_user, older_oldacct, single_highbalance, highbal_utilratio) %>%
  pivot_longer(cols = -Churn,names_to = "component",values_to = "loading") %>%
  ggplot(aes(loading, fill=Churn))+
  geom_density(alpha=0.5)+
  facet_grid(.~component)

```

#highest features
```{r}

#Find the features with the highest loadings per factor
rownames_to_column(as.data.frame(pr_bank$rotation)) %>%
  select(1:6) %>%
  filter(abs(PC1) >= 0.25 | abs(PC2) >= 0.25 | abs(PC3) >= 0.25 | abs(PC4) >= 0.25 | abs(PC5) >= 0.25)


#Name and graph the factors
prc <- bind_cols(select(bank1,Churn),as.data.frame(pr_bank$x)) %>%
  select(1:6) %>%
  rename("bluesilver_avgopen_credit"=PC1, "high_user"=PC2, "older_oldacct"=PC3, "single_highbalance"=PC4,
         "highbal_utilratio"=PC5)


prc %>%
  select(Churn, bluesilver_avgopen_credit,high_user) %>%
  pivot_longer(cols = -Churn,names_to = "component",values_to = "loading") %>%
    ggplot(aes(loading, fill=Churn))+
geom_density(alpha=0.5)+
facet_grid(.~component)

prc %>%
  select(Churn, older_oldacct,single_highbalance) %>%
  pivot_longer(cols = -Churn,names_to = "component",values_to = "loading") %>%
    ggplot(aes(loading, fill=Churn))+
geom_density(alpha=0.5)+
facet_grid(.~component)

prc %>%
  select(Churn, highbal_utilratio) %>%
  pivot_longer(cols = -Churn,names_to = "component",values_to = "loading") %>%
    ggplot(aes(loading, fill=Churn))+
geom_density(alpha=0.5)+
facet_grid(.~component)

```

#my first model
```{r}

#Use these factors for prediction
fit <- train(Churn ~ .,
             data = prc,
             method = "rf",
             metric = "Kappa",
             trControl = trainControl(method = "cv"))
#kappa .43
confusionMatrix(predict(fit, prc),factor(prc$Churn))


```

#template from Hendrik
## Specification

```{r}
# specify the model to be used (i.e. KNN, Naive Bayes, decision tree, random forest, bagged trees) and the tuning parameters used

ctrl <- trainControl(method = "cv", number = 3, classProbs=TRUE, summaryFunction = twoClassSummary)
set.seed(504) 

bank_index <- createDataPartition(banko$Churn, p = 0.80, list = FALSE)
train <- banko[ bank_index, ]
test <- banko[-bank_index, ]

# example spec for rf
fit <- train(Churn ~ .,
             data = train, 
             method = "rf",
             ntree = 20, 
             tuneLength = 3,
             metric = "ROC",
             trControl = ctrl)

fit

confusionMatrix(predict(fit, test),factor(test$Churn))
```


## Best model

```{r}
# Here are a few lines to inspect your best model. Add some comments about optimal hyperparameters.
print(fit)
print(fit$bestTune)
```


## Re-fit and evaluation

```{r}
# the "method" below should match the one you chose above. 

set.seed(1504) # I will choose a different seed for evaluation

bank_index <- createDataPartition(banko$Churn, p = 0.80, list = FALSE)
train <- banko[ bank_index, ]
test <- banko[-bank_index, ]

# example spec for rf
fit_final <- train(Churn ~ .,
             data = train, 
             method = "rf",
             tuneGrid=fit$bestTune,
             metric = "ROC",
             trControl = ctrl) 
# The last line means we will fit a model using the best tune parameters your CV found above.

myRoc <- roc(test$Churn, predict(fit_final, test, type="prob")[,2])

plot(myRoc)
auc(myRoc)
```

